### PR TITLE
Proper Department handling during import

### LINKED ISSUE #8: Add department association
The department association of a publication is stored in the `header/setSpec`

To get the meaning of the values of the setSpec it is necessary to get the sets from dspace using the `/oai/request?verb=ListSets` endpoint. 

This gives a long list of records (at ZHAW some 146 or so), so to requests are needed. These records hardly ever change for out needs. 

We need to build a lookup table from these records in order to set the departmental affiliation.

### PR DESCRIPTION
**Pull request by phish108**
The departmental association is not handled. fixes #8

### CODE REVIEW

**Comment by phish108** [comment]
Hey @sgluege  nicht reviewen bevor ich fertig bin :P

**Comment by sgluege** [comment]
> Hey @sgluege nicht reviewen bevor ich fertig bin :P

Woher weiss ich wann du fertig bist?

**Comment by phish108** [comment]
Easy, wenn nicht mehr Draft oben dran steht :)

**Comment by phish108** [comment]
@sgluege OK, ready for review. 

This PR has two parts: 

1. the new `get_deptcollection_from_xml_record_entity()` extracts the collections from the record header and determines to which department a record is related. I use a crude lookup table. It would be more elegant do load the collection names via `https://digitalcollection.zhaw.ch/oai/requets?verb=ListSets` and load the department mapping from a separate configuration file that does not have to be public. But for the time being this should do the trick. 

2. I refactored the GraphQL code to use Variables. This simplifies the code significantly and allows to get rid of the mapping functions, because the data can be passed directly to the `gql` client as a dictionary. 

I found a potential logical error in function `get_entity_from_xml_record_entity()`: You only test, whether the **first** element has some content and then assume that **all** elements have contents. This is not necessarily the case with XML documents. Do you think, we should refactor this code, too?

**Review by sgluege — APPROVED** [review]
looks legit :)

**Pull request merged**
